version: '3'
services:
  edm-hdfs-namenode:
    image: elastest/edm-hadoop:latest
    command: [ "sh", "-c", "/namenode.sh" ]
    privileged: true
    ports:
        - "50070:50070"
        - "9000:9000"
        - "8020:8020"
        - "8001:8001"
    hostname: edm-hdfs-namenode
    networks:
        - elastest

  edm-hdfs-datanode:
    image: elastest/edm-hadoop:latest
    command: hdfs datanode
    # The host port is randomly assigned by Docker,
    # to allow scaling to multiple DataNodes on the same host
    ports:
        - "50075"
    links:
        - edm-hdfs-namenode
    networks:
        - elastest

  edm-alluxio-master:
    image: elastest/edm-alluxio:latest
    command: master
    ports:
      - 19999:19999
      - 19998:19998
    volumes:
      - ./alluxio/data:/underStorage
    environment:
      - ALLUXIO_MASTER_HOSTNAME=edm-alluxio-master
      - ALLUXIO_UNDERFS_ADDRESS=/underStorage
    links:
        - edm-hdfs-namenode
    hostname: edm-alluxio-master
    networks:
        - elastest

  edm-alluxio-worker:
    # container_name: alluxio-worker
    image: elastest/edm-alluxio:latest
    # build: ./alluxio
    command: worker
    ports:
      - "29998"
      - "29999"
    volumes:
      - ./alluxio/data:/underStorage
    links:
      - edm-hdfs-namenode
      - edm-alluxio-master
    environment:
      - ALLUXIO_MASTER_HOSTNAME=edm-alluxio-master
      - ALLUXIO_RAM_FOLDER=/mnt/ramdisk
      - ALLUXIO_WORKER_MEMORY_SIZE=1GB
      - ALLUXIO_UNDERFS_ADDRESS=/underStorage
    networks:
        - elastest

  edm:
    image: elastest/edm:latest
    volumes:
      - ./rest-java/rest_api_project/deployment:/usr/local/tomcat/webapps
      - ./rest-java/alluxio_conf:/opt/alluxio/conf
      - ./backup:/backup
    environment:
      - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
      - ET_EDM_MYSQL_HOST=edm-mysql
      - ET_EDM_MYSQL_PORT=3306
      - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
      - ET_EDM_API=http://edm:37003/
      - ET_EPM_API=http://epm:37002/
      - ET_ETM_API=http://etm:37006/
      - ET_ESM_API=http://esm:37005/
      - ET_EIM_API=http://eim:37004/
      - ET_ETM_LSBEATS_HOST=etm-beats
      - ET_ETM_LSBEATS_PORT=5044
      - ET_ETM_LSHTTP_API=http://etm-logstash:5002/
      - ET_ETM_RABBIT_HOST=etm-rabbitmq
      - ET_ETM_RABBIT_PORT=5672
      - ET_EMP_API=http://eim:37001/
      - ET_EMP_INFLUXDB_API=http://emp-influxdb:8086/
      - ET_EMP_INFLUXDB_HOST=emp-influxdb
      - ET_EMP_INFLUXDB_GRAPHITE_PORT=2003
    links:
      - edm-alluxio-master
      - edm-elasticsearch
      - edm-mysql
    ports:
      - 37003:8080  # host:container
    networks:
        - elastest

  edm-alluxio-proxy:
    image: elastest/edm-alluxio:latest
    command: proxy
    ports:
      - 39999:39999
    volumes:
      - ./alluxio/data:/underStorage
    links:
      - edm-alluxio-worker
    environment:
      - ALLUXIO_MASTER_HOSTNAME=edm-alluxio-master
    networks:
        - elastest


  edm-elasticsearch:
    image: elastest/edm-elasticsearch:latest
    volumes:
      - esbackup:/backup
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - discovery.type=zen
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.zen.ping.unicast.hosts=edm-elasticsearch
      - discovery.zen.minimum_master_nodes=2
    hostname: edm-elasticsearch
    networks:
      - elastest


  esnode:
    image: elastest/edm-elasticsearch:latest
    volumes:
      - esbackup:/backup
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - "9200"
      - "9300"
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.type=zen
      - discovery.zen.ping.unicast.hosts=edm-elasticsearch
      - discovery.zen.minimum_master_nodes=2
    depends_on:
      - edm-elasticsearch
    hostname: esnode
    networks:
      - elastest


  edm_kibana:
    image: elastest/edm-kibana:latest
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.type=zen
      - discovery.zen.ping.unicast.hosts=edm-elasticsearch
    networks:
      - elastest
    depends_on:
      - edm-elasticsearch


  edm-cerebro:
    image: elastest/edm-cerebro:latest
    volumes:
      - ./cerebro/config:/opt/cerebro-0.6.5/conf
      - ./cerebro/logs:/opt/cerebro-0.6.5/logs
    depends_on:
      - edm-elasticsearch
    ports:
      - 9400:9000
    environment:
      - ELASTICSEARCH_HOST=http://edm-elasticsearch:9200
    tty: true
    networks:
      - elastest

  edm-mysql:
    image: elastest/edm-mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "elastest"
      MYSQL_USER: elastest
      MYSQL_PASSWORD: elastest
    volumes:
      - edm-mysql:/var/lib/mysql
    # restart: always
    networks:
      - elastest
volumes:
    esdata1:
      driver: local
    esdata2:
      driver: local
    esbackup:
      driver: local
    edm-mysql:
      driver: local

networks:
  elastest:
    external: true
    # driver: bridge
